### PR TITLE
Attempt to enable custom replshow methods

### PR DESCRIPTION
**Pull request by brenhinkeller**
A potential solution to #14. Could use some code review as to whether this is really the best way to do this.

### CODE REVIEW

**Comment by MasonProtter** [comment]
I love this. 
```julia
julia> begin
       backwards_show(io, M, x) = (show(io, M, x); println(io))
       backwards_show(io, M, v::Union{Vector, Tuple}) = (show(io, M, reverse(v)); println(io))

       using ReplMaker
       initrepl(Meta.parse,
           repl=enablecustomdisplay(Base.active_repl, backwards_show, stdout),
           prompt_text="reverse_julia> ",
           start_key=')',
           mode_name="reverse mode"
       )
       end
REPL mode reverse mode initialized. Press ) to enter and backspace to exit.
"Prompt(\"reverse_julia> \",...)"

reverse_julia> [1,2,3] .+ [4, 5, 6]
3-element Array{Int64,1}:
 9
 7
 5
```

**Comment by MasonProtter** [comment]
My only real comment is that maybe we should hide the creation of a new repl from `enablecustomdisplay` inside `initrepl` and then just have something like a `show_function` kwarg where you'd pass your own custom `show`?

**Comment by brenhinkeller** [comment]
Haha, the backwards Julia is awesome.

Yeah, I think we could definitely hide it inside initrepl. Should we also add an option to specify the iostream for custom displays? One thought would be having defaults along the lines of 
```
show_function = nothing, 
show_function_io = stdout
```
for the input arguments, and then within `initrepl` having a conditional
```
if ~isnothing(show_function)
    repl = enablecustomdisplay(repl, show_function, show_function_io)
end
```
such that a REPL that chooses not to use a custom `show_function` never has to follow any of the modified code paths for a repl with `specialdisplay` set to an instance of the new `CustomREPLDisplay` type, and can just use the normal Base paths.

**Comment by MasonProtter** [comment]
Yeah, I like both suggestions.

**Comment by brenhinkeller** [comment]
I think this should do it. Forgot that 1.0 doesn't have `isnothing` so switched back to `!= nothing` for the conditional

**Comment by MasonProtter** [comment]
Okay, this is great! Thanks Bernhin, sorry I haven't been able to be more responsive on this!

**Pull request merged**
