### PR TITLE
Provide a handy API to start REPL via a function instead of typing start key manually 

### PR DESCRIPTION
**Pull request by thautwarm**
```julia
julia> lang_mode =
       initrepl(parse_to_expr, 
                prompt_text="Expr> ",
                prompt_color = :blue, 
                start_key=')', 
                mode_name="Expr_mode")
julia> trans_mode!(lang_mode)
Expr> 
```

We can now enter other mode even when executing.

### CODE REVIEW

**Comment by thautwarm** [comment]
ReplMaker now gets something wrong when running tests with 1.0 LTS and nightly version.
Hence besides the main purpose of this PR, I'm also trying to fix the test errors.

**Comment by thautwarm** [comment]
@MasonProtter Hi, `__precompile__(false)` caused the failure of tests in Julia 1.0. Should I remove it?

**Comment by thautwarm** [comment]
Test error cannot get resolved in nightly, caused by
> `Unicode` is a direct dependency

**Comment by giordano** [comment]
What happens if you remove the Manifest.toml file?

**Comment by thautwarm** [comment]
@giordano  Just had a try and nothing happened.
I think Mason used to compat v0.7 so he did need Manifest.toml.
However now this package seems to work since 1.0 thus we can remove it(IMO

**Comment by MasonProtter** [comment]
Looks great! 

Could we change `trans_mode!` to maybe `enter_mode!`? I think that’s a bit more self explanatory. 

Removing `Manifest.toml` is fine.

**Comment by thautwarm** [comment]
Made modifications following your instructions.
Have a nice vacation!

**Comment by thautwarm** [comment]
@MasonProtter Hi,  want to use your repo in my talk on Aug 24. Can you merge before that?

**Comment by thautwarm** [comment]
Aug 24 UTC+8

**Comment by MasonProtter** [comment]
Merged, thanks again!

**Pull request merged**
